### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by kalemas**
There is a lot of nuances with building working 3d-Pack on linux environment, so having a reference in form of Dockerfile for working setup and such a quick way to get in working - would be very helpfull.

Unfortunately i still struggling with setup and cant get it completely working, so your advices would be helpful.

- [ ] CRM segfaults on inference
- [ ] all other modes require uninstalled custom nodes

### CODE REVIEW

**Comment by MrForExample** [comment]
Thanks friend 👍

**Comment by kalemas** [comment]
@MrForExample you are lighting fast) i ve [updated](https://github.com/kalemas/ComfyUI-3D-Pack/commit/91ee7a253a4c5cdd4c6a5fbfee7eccdc0304e96b) source branch with custom nodes required to run examples and still can't get it working properly :((

```
[Comfy3D] [Load_Triplane_Gaussian_Transformers] loaded model ckpt from /app/custom_nodes/ComfyUI-3D-Pack/checkpoints/tgs/model_lvis_rel.ckpt
/app/custom_nodes/ComfyUI-3D-Pack/tgs/data.py:91: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:63.)
  right: Float[Tensor, "B 3"] = F.normalize(torch.cross(lookat, up), dim=-1)
[Comfy3D] [Save_3DGS] Saving model to /app/output/MeshTest\3DGS_Picacho.ply
Number of points at loading :  16384
[F glutil.cpp:338] eglInitialize() failed
```
following happens whenever it comes to render 3d model

**Comment by kalemas** [comment]
Probably i have to install 3d-pack on host and get it running to ensure that this is host or container issue. Could someone confirm `eglInitialize() failed` issue?

**Comment by WorkSync** [comment]
> Probably i have to install 3d-pack on host and get it running to ensure that this is host or container issue. Could someone confirm `eglInitialize() failed` issue?也许我必须在主机上安装 3d-pack 并让它运行以确保这是主机或容器问题。有人可以确认 `eglInitialize() failed` 问题吗？

Hey,dear.Have you solved it?

**Pull request merged**
