### PR TITLE
download button added

### PR DESCRIPTION
**Pull request by yashschandra**
To download glb or other model files loaded in the visualizer, otherwise we have to copy file from server's output folder.

https://github.com/user-attachments/assets/fbfcac31-9b36-48f7-9ea0-e480d7d076c3

@MrForExample If this PR looks ok then can you please test it once locally. I tested it on my local machine with some workarounds in place (because macos 😞 )

### CODE REVIEW

**Comment by MrForExample** [comment]
Thank you for your contribution 👍

**Comment by yashschandra** [comment]
@MrForExample it already downloads with correct extension, checked with .glb and .obj files

**Comment by QianquanChina** [comment]
Thank you for your contribution!!!!!!
When my `comfyui` is not deployed locally, it will not be displayed normally.
I have added client IP in `configs/system.conf` file.
Do you have this problem? Thanks 🙇‍

**Comment by WorkSync** [comment]
> To download glb or other model files loaded in the visualizer, otherwise we have to copy file from server's output folder.
> 
>  Screen.Recording.2024-07-13.at.9.45.00.PM.mov 
> @MrForExample If this PR looks ok then can you please test it once locally. I tested it on my local machine with some workarounds in place (because macos 😞 )

Hello, thank you for your great contribution. I wonder how to right-click the node, and then download in the menu, then how should I implement it?
Specifically, it is in the folder--"web/scripts/app.js"，and code --"node.prototype.getExtraMenuOptions = function (_, options)".

**Comment by yashschandra** [comment]
> Thank you for your contribution!!!!!! When my `comfyui` is not deployed locally, it will not be displayed normally. I have added client IP in `configs/system.conf` file. Do you have this problem? Thanks 🙇‍

Hello @QianquanChina I never had to configure any IPs in the `conf` file. I have always hosted ComfyUI on a normal vm instance behind an nginx server.

**Comment by yashschandra** [comment]
> > To download glb or other model files loaded in the visualizer, otherwise we have to copy file from server's output folder.
> > Screen.Recording.2024-07-13.at.9.45.00.PM.mov
> > @MrForExample If this PR looks ok then can you please test it once locally. I tested it on my local machine with some workarounds in place (because macos 😞 )
> 
> Hello, thank you for your great contribution. I wonder how to right-click the node, and then download in the menu, then how should I implement it? Specifically, it is in the folder--"`web/scripts/app.js`"，and code --"`node.prototype.getExtraMenuOptions = function (_, options)`".

@WorkSync I never though of doing it like that but I think that would be better than just adding a button. Did you figure out any way to implement it? I haven't looked at it yet.

**Pull request merged**
